### ISSUE TITLE
How to specify private key password?

### ISSUE THREAD

**Issue by waynehaffenden** [RealOrangeOne/docker-lsyncd#2]
How do you specify the private key password?

**Comment by RealOrangeOne** [comment]
This is more a question for `lsyncd` than this container.

In theory you'd specify it in the same way you specify it to `rsync`, which is used under the hood. If `rsync` has the option to provide, then you can specify it in the config. See https://axkibe.github.io/lsyncd/manual/config/layer4/ for more config details.

Given this isn't something the container deals with, i'm going to close the issue.
