### ISSUE TITLE
update image

### ISSUE THREAD

**Issue by terryzwt** [RealOrangeOne/docker-lsyncd#22]
The lsyncd latest version is 2.3.1, see below:
https://github.com/lsyncd/lsyncd/releases

The lsyncd version in docker image is 2.2.3, please help to update the docker image.
<img width="324" alt="image" src="https://github.com/user-attachments/assets/f40ff924-1fbc-4705-ac39-23a499bdf0ec">

**Comment by RealOrangeOne** [comment]
With https://github.com/RealOrangeOne/docker-lsyncd/commit/c7e3b5b419de8b43595bd086a1d0ca2cc576f591, the image should be rebuilt, and a newer version of `lsyncd` used.
